
export const urlConstants = {

    FORMAT_DATE: (date) => date.getFullYear() + ('0' + (date.getMonth() + 1)).slice(-2) + ('0' + date.getDate()).slice(-2),

    GET_TEAM_LOGO: (tricode) => `https://www.nba.com/.element/img/1.0/teamsites/logos/teamlogos_500x500/${tricode.toLowerCase()}.png`,

    API_BASE: 'http://data.nba.net/10s/prod',

};

export const TEAM_NAMES = {
    USA: 'USA',
    WLD: 'World',
    EST: 'All-Stars',
    WST: 'All-Stars',
    GNS: 'Team Giannis',
    LBN: 'Team LeBron',
    DRT: 'Team K D',
    AFR: 'Team Africa',
    ADL: 'Adelaide 36ers',
    ATL: 'Atlanta Hawks',
    BJD: 'Beijing Ducks',
    BOS: 'Boston Celtics',
    BKN: 'Brooklyn Nets',
    CHA: 'Charlotte Hornets',
    CHI: 'Chicago Bulls',
    CLE: 'Cleveland Cavaliers',
    DAL: 'Dallas Mavericks',
    DEN: 'Denver Nuggets',
    DET: 'Detroit Pistons',
    GSW: 'Golden State Warriors',
    GUA: 'Guangzhou Long-Lions',
    MAC: 'Maccabi Haifa',
    HOU: 'Houston Rockets',
    IND: 'Indiana Pacers',
    LAC: 'LA Clippers',
    LAL: 'Los Angeles Lakers',
    MEL: 'Melbourne United',
    MEM: 'Memphis Grizzlies',
    MIA: 'Miami Heat',
    MIL: 'Milwaukee Bucks',
    MIN: 'Minnesota Timberwolves',
    NOP: 'New Orleans Pelicans',
    NYK: 'New York Knicks',
    NZB: 'New Zealand Breakers',
    OKC: 'Oklahoma City Thunder',
    ORL: 'Orlando Magic',
    PER: 'Perth Wildcats',
    PHI: 'Philadelphia 76ers',
    PHX: 'Phoenix Suns',
    POR: 'Portland Trail Blazers',
    FLA: 'Rio de Janeiro Flamengo',
    SAC: 'Sacramento Kings',
    SAS: 'San Antonio Spurs',
    SDS: 'Shanghai Sharks',
    SYD: 'Sydney Kings',
    TOR: 'Toronto Raptors',
    UTA: 'Utah Jazz',
    WAS: 'Washington Wizards',
};
