// General

export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';

//Stats

export const SET_GAMES_BY_DAY = 'SET_GAMES_BY_DAY';
export const SET_GAME_DETAILS = 'SET_GAME_DETAILS';
export const SET_STANDINGS_CONFERENCE = 'SET_STANDINGS_CONFERENCE';
